import type { Listing, Profile } from "./types";

/**
 * Données de démonstration utilisées quand Supabase n'est pas configuré
 * (aperçu du site, développement local, revue design).
 */
const now = new Date().toISOString();

export const demoProfiles: Profile[] = [
  {
    id: "p-eleveur-1",
    role: "eleveur",
    display_name: "Élevage du Vallon",
    slug: "elevage-du-vallon",
    avatar_url: null,
    phone: "06 00 00 00 01",
    email: null,
    bio: "Élevage familial de Selle Français orientés CSO depuis 1998, en Isère. Poulains élevés au pré en troupeau, manipulés dès la naissance.",
    city: "Montaud",
    postal_code: "38210",
    region: "Auvergne-Rhône-Alpes",
    siret: "123 456 789 00012",
    company_name: "EARL Élevage du Vallon",
    website: null,
    is_verified: true,
    is_admin: true,
    is_blocked: false,
    verification_note: null,
    charter_accepted_at: now,
    created_at: now,
  },
  {
    id: "p-pro-1",
    role: "pro_depot",
    display_name: "Écurie Horizon – dépôt-vente",
    slug: "ecurie-horizon",
    avatar_url: null,
    phone: "06 00 00 00 02",
    email: null,
    bio: "Écurie de valorisation et dépôt-vente en Normandie. Nous présentons chaque cheval avec vidéo récente, radios disponibles et essai monté sur place.",
    city: "Saint-Lô",
    postal_code: "50000",
    region: "Normandie",
    siret: "987 654 321 00021",
    company_name: "SARL Écurie Horizon",
    website: null,
    is_verified: true,
    is_admin: false,
    is_blocked: false,
    verification_note: null,
    charter_accepted_at: now,
    created_at: now,
  },
  {
    id: "p-part-1",
    role: "particulier",
    display_name: "Claire M.",
    slug: null,
    avatar_url: null,
    phone: "06 00 00 00 03",
    email: null,
    bio: "Propriétaire amateur, je vends mon cheval à contrecœur pour raison de reprise d'études.",
    city: "Rennes",
    postal_code: "35000",
    region: "Bretagne",
    siret: null,
    company_name: null,
    website: null,
    is_verified: false,
    is_admin: false,
    is_blocked: false,
    verification_note: null,
    charter_accepted_at: now,
    created_at: now,
  },
  {
    id: "p-acheteur-1",
    role: "acheteur",
    display_name: "Julien D.",
    slug: null,
    avatar_url: null,
    phone: null,
    email: null,
    bio: null,
    city: "Lyon",
    postal_code: "69000",
    region: "Auvergne-Rhône-Alpes",
    siret: null,
    company_name: null,
    website: null,
    is_verified: false,
    is_admin: false,
    is_blocked: false,
    verification_note: null,
    charter_accepted_at: now,
    created_at: now,
  },
];

function seller(id: string) {
  const p = demoProfiles.find((x) => x.id === id)!;
  return {
    id: p.id,
    display_name: p.display_name,
    role: p.role,
    is_verified: p.is_verified,
    city: p.city,
    region: p.region,
    avatar_url: p.avatar_url,
    slug: p.slug,
    company_name: p.company_name,
  };
}

const base = {
  status: "active" as const,
  owner_name: null,
  temperament: null,
  studbook_approved: false,
  dam_sire_name: null,
  price_hidden: false,
  price_negotiable: false,
  vat_included: true,
  postal_code: null,
  video_urls: [] as string[],
  vet_check_available: true,
  xrays_available: false,
  trial_available: true,
  visit_available: true,
  competition_results: null,
  health_notes: null,
  known_vices: null,
  featured: false,
  moderation_note: null,
  views_count: 0,
  created_at: now,
  updated_at: now,
  published_at: now,
};

export const demoListings: Listing[] = [
  {
    ...base,
    id: "l1",
    slug: "quartz-du-vallon-sf-4-ans-cso",
    seller_id: "p-eleveur-1",
    seller: seller("p-eleveur-1"),
    is_depot_vente: false,
    title: "Quartz du Vallon – SF 4 ans par Diamant de Semilly, avenir CSO",
    horse_name: "Quartz du Vallon",
    breed: "Selle Français",
    sex: "hongre",
    birth_year: new Date().getFullYear() - 4,
    height_cm: 168,
    color: "Bai",
    disciplines: ["CSO", "Hunter"],
    level: "debourre",
    description:
      "Quartz est un hongre de 4 ans né chez nous, débourré à l'automne dans le calme. Il sort en cycles classiques 4 ans cette saison : 4 sans-faute sur 5 sorties. Très respectueux, beaucoup de moyens, mental de compétiteur sans être chaud. Élevé au pré en troupeau, ferré des antérieurs, vermifugé et vacciné à jour.\n\nIl conviendra à un cavalier amateur souhaitant former un cheval pour le 1,20 m et plus. Visible à l'élevage en Isère, essai monté possible sur rendez-vous, radios de 3 ans disponibles.",
    temperament: "Calme, respectueux, franc à l'obstacle. Vit au pré avec d'autres chevaux.",
    sire_number: "23000123456A",
    papers: "sire_full",
    studbook_approved: false,
    sire_name: "Diamant de Semilly",
    dam_name: "Onyx du Vallon",
    dam_sire_name: "Quidam de Revel",
    price: 18000,
    price_negotiable: true,
    city: "Montaud",
    region: "Auvergne-Rhône-Alpes",
    photos: ["/demo/horse-1.svg", "/demo/horse-3.svg", "/demo/horse-5.svg"],
    video_urls: ["https://www.youtube.com/watch?v=dQw4w9WgXcQ"],
    xrays_available: true,
    competition_results: "Cycles classiques 4 ans : 4 sans-faute / 5 sorties (2026).",
    featured: true,
    views_count: 342,
  },
  {
    ...base,
    id: "l2",
    slug: "tango-hongre-loisir-12-ans",
    seller_id: "p-part-1",
    seller: seller("p-part-1"),
    is_depot_vente: false,
    title: "Tango – hongre 12 ans, cheval de loisir idéal, pied sûr en extérieur",
    horse_name: "Tango",
    breed: "Origine constatée (OC)",
    sex: "hongre",
    birth_year: new Date().getFullYear() - 12,
    height_cm: 158,
    color: "Alezan",
    disciplines: ["Loisir / balade", "Randonnée", "Dressage"],
    level: "club",
    description:
      "Je vends Tango, mon cheval de cœur, car je reprends des études à l'étranger. Il est parfait en extérieur seul ou en groupe, ne bronche pas devant les voitures, tracteurs ou vélos. Il a sorti quelques Club 2 en dressage. Il est facile à ferrer, à doucher, monte en van sans hésiter.\n\nIl a besoin d'une monte douce et régulière ; il conviendrait à un cavalier de club souhaitant passer propriétaire, ou à une famille. Pas de vice caché, pas de blessure, radios de 2025 disponibles.",
    temperament: "Très gentil, un peu paresseux, adore les câlins.",
    sire_number: "23000987654B",
    papers: "oc",
    sire_name: null,
    dam_name: null,
    price: 4500,
    price_negotiable: true,
    city: "Rennes",
    region: "Bretagne",
    photos: ["/demo/horse-2.svg", "/demo/horse-6.svg"],
    xrays_available: true,
    views_count: 511,
  },
  {
    ...base,
    id: "l3",
    slug: "galway-kwpn-9-ans-130-depot-vente",
    seller_id: "p-pro-1",
    seller: seller("p-pro-1"),
    is_depot_vente: true,
    owner_name: "Propriétaire particulier",
    title: "Galway – KWPN 9 ans, expérience 1,30 m, en dépôt-vente",
    horse_name: "Galway",
    breed: "KWPN",
    sex: "jument",
    birth_year: new Date().getFullYear() - 9,
    height_cm: 171,
    color: "Bai brun",
    disciplines: ["CSO"],
    level: "amateur",
    description:
      "Jument de 9 ans en dépôt-vente à l'écurie, expérience régulière en Amateur Elite 1,30 m avec de nombreux classements. Très respectueuse, facile dans les tournants, style de saut moderne. Elle monte en van, vit en box avec paddock quotidien, aucune pathologie connue.\n\nVidéos de concours récentes disponibles sur demande, radios complètes 2026 consultables par votre vétérinaire. Essai à l'écurie en Normandie sur rendez-vous, le mandat de dépôt-vente est consultable par l'acheteur.",
    temperament: "Sensible mais généreuse, cavalier confirmé conseillé.",
    sire_number: "52800012345C",
    papers: "foreign",
    sire_name: "Zirocco Blue",
    dam_name: "Wendela",
    price: 45000,
    vat_included: false,
    city: "Saint-Lô",
    region: "Normandie",
    photos: ["/demo/horse-3.svg", "/demo/horse-7.svg", "/demo/horse-9.svg"],
    xrays_available: true,
    competition_results: "Classée 12 fois en Amateur Elite 2025-2026.",
    featured: true,
    views_count: 780,
  },
  {
    ...base,
    id: "l4",
    slug: "opale-pouliche-2-ans-sf-eleveur",
    seller_id: "p-eleveur-1",
    seller: seller("p-eleveur-1"),
    is_depot_vente: false,
    title: "Opale du Vallon – pouliche SF 2 ans, souche maternelle performante",
    horse_name: "Opale du Vallon",
    breed: "Selle Français",
    sex: "pouliche",
    birth_year: new Date().getFullYear() - 2,
    height_cm: null,
    color: "Gris",
    disciplines: ["CSO", "Élevage / reproduction"],
    level: "poulain",
    description:
      "Pouliche de 2 ans, très bien née : mère internationale 1,45 m, sœur utérine en Grand Prix. Modèle harmonieux, allures amples, très bon caractère. Manipulée quotidiennement, marche en main, monte en van. Idéale pour un projet sport ou reproduction.\n\nVendue avec ses papiers SF complets, carte d'immatriculation à jour.",
    temperament: "Curieuse et confiante.",
    sire_number: "23000456789D",
    papers: "sire_full",
    sire_name: "Contendro",
    dam_name: "Jade du Vallon",
    dam_sire_name: "Kannan",
    price: 9000,
    city: "Montaud",
    region: "Auvergne-Rhône-Alpes",
    photos: ["/demo/horse-4.svg"],
    trial_available: false,
    views_count: 120,
  },
  {
    ...base,
    id: "l5",
    slug: "biscotte-poney-connemara-d-club",
    seller_id: "p-part-1",
    seller: seller("p-part-1"),
    is_depot_vente: false,
    title: "Biscotte – poney D Connemara 10 ans, club et amateur",
    horse_name: "Biscotte",
    breed: "Connemara",
    sex: "jument",
    birth_year: new Date().getFullYear() - 10,
    height_cm: 146,
    color: "Isabelle",
    disciplines: ["CSO", "Équifun / poney club", "Complet"],
    level: "club",
    description:
      "Ponette D très polyvalente, a fait le bonheur de ma fille en Poney 2 et 1. Sort en CSO club, hunter et petit complet. Facile en tout, vit dehors, sans vice. Ma fille passe à cheval, nous cherchons une famille sérieuse.",
    temperament: "Volontaire, douce avec les enfants.",
    sire_number: "23000222333E",
    papers: "sire_full",
    sire_name: null,
    dam_name: null,
    price: 7500,
    city: "Rennes",
    region: "Bretagne",
    photos: ["/demo/horse-5.svg", "/demo/horse-8.svg"],
    views_count: 260,
  },
  {
    ...base,
    id: "l6",
    slug: "nino-lusitanien-dressage-7-ans",
    seller_id: "p-pro-1",
    seller: seller("p-pro-1"),
    is_depot_vente: true,
    owner_name: "Élevage partenaire (Portugal)",
    title: "Nino – Lusitanien 7 ans, dressage jusqu'au Saint-Georges",
    horse_name: "Nino",
    breed: "Lusitanien",
    sex: "entier",
    birth_year: new Date().getFullYear() - 7,
    height_cm: 163,
    color: "Gris",
    disciplines: ["Dressage"],
    level: "amateur",
    description:
      "Entier Lusitanien approuvé, travail confirmé jusqu'au niveau Saint-Georges : changements de pied au temps, pirouettes, début de passage. Très agréable au quotidien, se monte en carrière comme en extérieur. Il est présenté à l'écurie en dépôt-vente pour le compte de son éleveur.",
    temperament: "Volontaire, à l'écoute, respectueux malgré son statut d'entier.",
    sire_number: "62000111222F",
    papers: "foreign",
    studbook_approved: true,
    sire_name: "Rubi AR",
    dam_name: "Dama",
    price: 32000,
    vat_included: false,
    city: "Saint-Lô",
    region: "Normandie",
    photos: ["/demo/horse-6.svg", "/demo/horse-10.svg"],
    xrays_available: true,
    views_count: 455,
  },
  {
    ...base,
    id: "l7",
    slug: "comtois-attelage-trait-8-ans",
    seller_id: "p-eleveur-1",
    seller: seller("p-eleveur-1"),
    is_depot_vente: false,
    title: "Uranie – jument Comtoise 8 ans, attelage et travail au sol",
    horse_name: "Uranie",
    breed: "Comtois",
    sex: "jument",
    birth_year: new Date().getFullYear() - 8,
    height_cm: 155,
    color: "Alezan",
    disciplines: ["Attelage", "Loisir / balade"],
    level: "club",
    description:
      "Jument de trait Comtoise, attelée en simple et en paire, habituée au débardage léger et aux sorties touristiques. Pleine pour le printemps prochain (saillie par un étalon Comtois approuvé). Très facile de caractère.",
    temperament: "Placide et travailleuse.",
    sire_number: "23000333444G",
    papers: "sire_full",
    sire_name: null,
    dam_name: null,
    price: 5200,
    city: "Montaud",
    region: "Auvergne-Rhône-Alpes",
    photos: ["/demo/horse-7.svg"],
    views_count: 88,
  },
  {
    ...base,
    id: "l8",
    slug: "cheval-compagnie-retraite-20-ans",
    seller_id: "p-part-1",
    seller: seller("p-part-1"),
    is_depot_vente: false,
    title: "Câline – jument 20 ans, cheval de compagnie, à placer contre bons soins",
    horse_name: "Câline",
    breed: "Origine non constatée (ONC)",
    sex: "jument",
    birth_year: new Date().getFullYear() - 20,
    height_cm: 152,
    color: "Noir",
    disciplines: ["Compagnie"],
    level: "retraite",
    description:
      "Câline est à la retraite après une carrière de club. Elle cherche une famille pour finir ses jours au pré avec des compagnons. Elle est en bonne santé, a des dents suivies et un régime adapté à son âge. Nous demandons un prix symbolique et une visite du lieu de vie avant toute cession. Contrat de vente avec clause de non-exploitation et droit de retour.",
    temperament: "Très douce, hiérarchie basse dans un troupeau.",
    sire_number: "23000555666H",
    papers: "onc",
    sire_name: null,
    dam_name: null,
    price: 300,
    city: "Rennes",
    region: "Bretagne",
    photos: ["/demo/horse-8.svg"],
    trial_available: false,
    views_count: 199,
  },
];
